# The URL the site will be built for
base_url = "https://bevy.org"

# Used for the Atom feed
title = "Bevy Engine"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
feed_limit = 1000

taxonomies = [{ name = "news", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

# Load extra syntaxes (e.g. WGSL) for syntax highlighting
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
# Put all your custom variables here
