[package]
name = "generate-community"
authors = ["Bevy Contributors <support@bevy.org>"]
license = "MIT"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.9"
rand = "0.8"
unicode-segmentation = "1.10"

[lints]
workspace = true
