[[release_notes]]
title = "`bevy_color`: a beautiful color solution"
authors = [
	"@viridia",
	"@alice-i-cecile",
	"@Earthmark",
	"@mockersf",
	"@pablo-lua",
	"@solis-lumine-vorago",
	"@NthTensor",
	"@bushrat001899",
	"@rparrett",
	"@afonsolage",
	"@chompaa",
	"@oyasumi731",
]
url = "https://github.com/bevyengine/bevy/pull/12013"
file_name = "12013_Upstreaming_bevy_color.md"

[[release_notes]]
title = "Immediately apply deferred system params in System::run"
authors = ["@james7132","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/11823"
file_name = "11823_Immediately_apply_deferred_system_params_in_Systemrun.md"

[[release_notes]]
title = "Run the multi-threaded executor at the end of each system task."
authors = ["@chescock","@hymm","@james7132"]
url = "https://github.com/bevyengine/bevy/pull/11906"
file_name = "11906_Run_the_multithreaded_executor_at_the_end_of_each_system_t.md"

[[release_notes]]
title = "Cubic splines overhaul"
authors = ["@JohnTheCoolingFan","@Jondolf","@alice-i-cecile","@IQuick143","@NthTensor"]
url = "https://github.com/bevyengine/bevy/pull/10701"
file_name = "10701_Cubic_splines_overhaul.md"

[[release_notes]]
title = "Add coordinate axes gizmo"
authors = ["@mweatherley"]
url = "https://github.com/bevyengine/bevy/pull/12211"
file_name = "12211_Add_coordinate_axes_gizmo.md"

[[release_notes]]
title = "Add basic light gizmos"
authors = ["@Kanabenki","@MrGVSV"]
url = "https://github.com/bevyengine/bevy/pull/12228"
file_name = "12228_Add_basic_light_gizmos.md"

[[release_notes]]
title = "Decouple `BackgroundColor` from `UiImage`"
authors = ["@benfrankel"]
url = "https://github.com/bevyengine/bevy/pull/11165"
file_name = "11165_Decouple_BackgroundColor_from_UiImage.md"

[[release_notes]]
title = "Add WinitEvent aggregate event for synchronized window event reading"
authors = ["@UkoeHB"]
url = "https://github.com/bevyengine/bevy/pull/12100"
file_name = "12100_Add_WinitEvent_aggregate_event_for_synchronized_window_eve.md"

[[release_notes]]
title = "bevy_reflect: Recursive registration"
authors = ["@MrGVSV","@soqb","@cart","@james7132"]
url = "https://github.com/bevyengine/bevy/pull/5781"
file_name = "5781_bevy_reflect_Recursive_registration.md"

[[release_notes]]
title = "Implement the `AnimationGraph`, allowing for multiple animations to be blended together."
authors = ["@pcwalton","@rparrett"]
url = "https://github.com/bevyengine/bevy/pull/11989"
file_name = "11989_Implement_the_AnimationGraph_allowing_for_multiple_animati.md"

[[release_notes]]
title = "Query Joins"
authors = ["@hymm","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/11535"
file_name = "11535_Query_Joins.md"

[[release_notes]]
title = "Add `Rotation2d`"
authors = ["@Jondolf","@IQuick143","@RobWalt","@tguichaoua"]
url = "https://github.com/bevyengine/bevy/pull/11658"
file_name = "11658_Add_Rotation2d.md"

[[release_notes]]
title = "Gizmo line joints"
authors = ["@solis-lumine-vorago","@pablo-lua"]
url = "https://github.com/bevyengine/bevy/pull/12252"
file_name = "12252_Gizmo_line_joints.md"

[[release_notes]]
title = "Gizmo 3d grids"
authors = ["@solis-lumine-vorago","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/12430"
file_name = "12430_Gizmo_3d_grids.md"

[[release_notes]]
title = "Alignment API for Transforms"
authors = ["@mweatherley"]
url = "https://github.com/bevyengine/bevy/pull/12187"
file_name = "12187_Alignment_API_for_Transforms.md"

[[release_notes]]
title = "Uniform point sampling methods for some primitive shapes."
authors = ["@13ros27"]
url = "https://github.com/bevyengine/bevy/pull/12484"
file_name = "12484_Uniform_point_sampling_methods_for_some_primitive_shapes.md"

[[release_notes]]
title = "Add pipeline statistics"
authors = ["@LeshaInc","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/9135"
file_name = "9135_Add_pipeline_statistics.md"

[[release_notes]]
title = "Add a gizmo-based overlay to show UI node outlines (Adopted)"
authors = ["@pablo-lua","@alice-i-cecile","@nicopap"]
url = "https://github.com/bevyengine/bevy/pull/11237"
file_name = "11237_Add_a_gizmobased_overlay_to_show_UI_node_outlines_Adopted.md"

[[release_notes]]
title = "Add border radius to UI nodes (adopted)"
authors = ["@chompaa","@pablo-lua","@bushrat011899","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/12500"
file_name = "12500_Add_border_radius_to_UI_nodes_adopted.md"

[[release_notes]]
title = "Add `Triangle3d` primitive to `bevy_math::primitives`"
authors = ["@vitorfhc","@NthTensor","@Jondolf"]
url = "https://github.com/bevyengine/bevy/pull/12508"
file_name = "12508_Add_Triangle3d_primitive_to_bevy_mathprimitives.md"

[[release_notes]]
title = "Meshlet rendering (initial feature)"
authors = ["@JMS55","@mockersf","@atlv24","@ricky26"]
url = "https://github.com/bevyengine/bevy/pull/10164"
file_name = "10164_Meshlet_rendering_initial_feature.md"

[[release_notes]]
title = "Get Bevy building for WebAssembly with multithreading"
authors = ["@kettle11","@daxpedda","@mockersf","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/12205"
file_name = "12205_Get_Bevy_building_for_WebAssembly_with_multithreading.md"

[[release_notes]]
title = "Gizmo line styles"
authors = ["@solis-lumine-vorago","@BD103"]
url = "https://github.com/bevyengine/bevy/pull/12394"
file_name = "12394_Gizmo_line_styles.md"

[[release_notes]]
title = "Move `Point` out of cubic splines module and expand it"
authors = ["@mweatherley","@bushrat011899"]
url = "https://github.com/bevyengine/bevy/pull/12747"
file_name = "12747_Move_Point_out_of_cubic_splines_module_and_expand_it.md"

[[release_notes]]
title = "Support wireframes for 2D meshes"
authors = ["@msvbg","@IceSentry"]
url = "https://github.com/bevyengine/bevy/pull/12135"
file_name = "12135_Support_wireframes_for_2D_meshes.md"

[[release_notes]]
title = "Improve performance by binning together opaque items instead of sorting them."
authors = ["@pcwalton","@james7132"]
url = "https://github.com/bevyengine/bevy/pull/12453"
file_name = "12453_Improve_performance_by_binning_together_opaque_items_inste.md"

[[release_notes]]
title = "Add `AsyncSeek` trait to `Reader` to be able to seek inside asset loaders"
authors = ["@BeastLe9enD"]
url = "https://github.com/bevyengine/bevy/pull/12547"
file_name = "12547_Add_AsyncSeek_trait_to_Reader_to_be_able_to_seek_inside_as.md"

[[release_notes]]
title = "Add `Tetrahedron` primitive to `bevy_math::primitives`"
authors = ["@Chubercik"]
url = "https://github.com/bevyengine/bevy/pull/12688"
file_name = "12688_Add_Tetrahedron_primitive_to_bevy_mathprimitives.md"

[[release_notes]]
title = "Add methods `iter_resources` and `iter_resources_mut`"
authors = ["@matiqo15","@pablo-lua","@james7132","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/12829"
file_name = "12829_Add_methods_iter_resources_and_iter_resources_mut.md"

[[release_notes]]
title = "Better information about why asset loading failed"
authors = ["@bugsweeper"]
url = "https://github.com/bevyengine/bevy/pull/12709"
file_name = "12709_Error_info_has_been_added_to_LoadStateFailed.md"

[[release_notes]]
title = "Implement percentage-closer filtering (PCF) for point lights."
authors = ["@pcwalton"]
url = "https://github.com/bevyengine/bevy/pull/12910"
file_name = "12910_Implement_percentagecloser_filtering_PCF_for_point_lights.md"

[[release_notes]]
title = "Optimize Event Updates"
authors = ["@james7132","@jdm","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/12936"
file_name = "12936_Optimize_Event_Updates.md"

[[release_notes]]
title = "Make `AppExit` more specific about exit reason."
authors = ["@Brezak","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/13022"
file_name = "13022_Make_AppExit_more_specific_about_exit_reason.md"

[[release_notes]]
title = "Contextually clearing gizmos"
authors = ["@Aceeri"]
url = "https://github.com/bevyengine/bevy/pull/10973"
file_name = "10973_Contextually_clearing_gizmos.md"

[[release_notes]]
title = "Improve par_iter and Parallel"
authors = ["@re0312","@james7132"]
url = "https://github.com/bevyengine/bevy/pull/12904"
file_name = "12904_Improve_par_iter_and_Parallel.md"

[[release_notes]]
title = "Meshlet continuous LOD"
authors = ["@JMS55","@pcwalton","@ricky26","@mockersf","@atlv24"]
url = "https://github.com/bevyengine/bevy/pull/12755"
file_name = "12755_Meshlet_continuous_LOD.md"

[[release_notes]]
title = "Make dynamic_linking a no-op on wasm targets"
authors = ["@james7132","@BD103"]
url = "https://github.com/bevyengine/bevy/pull/12672"
file_name = "12672_Make_dynamic_linking_a_noop_on_wasm_targets.md"

[[release_notes]]
title = "Per-Object Motion Blur"
authors = ["@aevyrie","@torsteingrindvik"]
url = "https://github.com/bevyengine/bevy/pull/9924"
file_name = "9924_PerObject_Motion_Blur.md"

[[release_notes]]
title = "Throttle render assets"
authors = ["@robtfm","@IceSentry","@mockersf"]
url = "https://github.com/bevyengine/bevy/pull/12622"
file_name = "12622_Throttle_render_assets.md"

[[release_notes]]
title = "Implement GPU frustum culling."
authors = ["@pcwalton"]
url = "https://github.com/bevyengine/bevy/pull/12889"
file_name = "12889_Implement_GPU_frustum_culling.md"

[[release_notes]]
title = "Upgrade to Taffy 0.4"
authors = ["@nicoburns"]
url = "https://github.com/bevyengine/bevy/pull/10690"
file_name = "10690_Upgrade_to_Taffy_04.md"

[[release_notes]]
title = "Computed States & SubStates"
authors = ["@lee-orr", "@MiniaczQ", "@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/11426"
file_name = "11426_Computed_State__Sub_States.md"

[[release_notes]]
title = "Working groups"
authors = ["@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/13162"
file_name = "13162_Add_a_process_for_working_groups.md"

[[release_notes]]
title = "Add BufferVec, an higher-performance alternative to StorageBuffer, and make GpuArrayBuffer use it."
authors = ["@kristoff3r","@alice-i-cecile","@IceSentry","@pcwalton"]
url = "https://github.com/bevyengine/bevy/pull/13199"
file_name = "13199_Add_BufferVec_an_higherperformance_alternative_to_StorageB.md"

[[release_notes]]
title = "Add `Annulus`-gizmos"
authors = ["@solis-lumine-vorago"]
url = "https://github.com/bevyengine/bevy/pull/13233"
file_name = "13233_Add_Annulusgizmos.md"

[[release_notes]]
title = "Extrusion"
authors = ["@solis-lumine-vorago","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/13270"
file_name = "13270_Extrusion.md"

[[release_notes]]
title = "Add UV channel selection to StandardMaterial"
authors = ["@geckoxx"]
url = "https://github.com/bevyengine/bevy/pull/13200"
file_name = "13200_Add_UV_channel_selection_to_StandardMaterial.md"

[[release_notes]]
title = "Implement fast depth of field as a postprocessing effect."
authors = ["@pcwalton","@Kurble","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/13009"
file_name = "13009_Implement_fast_depth_of_field_as_a_postprocessing_effect.md"

[[release_notes]]
title = "Add Rounded box gizmos"
authors = ["@solis-lumine-vorago","@jgayfer","@JMS55"]
url = "https://github.com/bevyengine/bevy/pull/11948"
file_name = "11948_Add_Rounded_box_gizmos.md"

[[release_notes]]
title = "Implement volumetric fog and volumetric lighting, also known as light shafts or god rays."
authors = ["@pcwalton"]
url = "https://github.com/bevyengine/bevy/pull/13057"
file_name = "13057_Implement_volumetric_fog_and_volumetric_lighting_also_know.md"

[[release_notes]]
title = "Add `on_unimplemented` Diagnostics to Most Public Traits"
authors = ["@bushrat011899","@alice-i-cecile","@Themayu","@BD103"]
url = "https://github.com/bevyengine/bevy/pull/13347"
file_name = "13347_Add_on_unimplemented_Diagnostics_to_Most_Public_Traits.md"

[[release_notes]]
title = "bevy_reflect: Custom attributes"
authors = ["@MrGVSV"]
url = "https://github.com/bevyengine/bevy/pull/11659"
file_name = "11659_bevy_reflect_Custom_attributes.md"

[[release_notes]]
title = "Deprecate dynamic plugins"
authors = ["@BD103"]
url = "https://github.com/bevyengine/bevy/pull/13080"
file_name = "13080_Deprecate_dynamic_plugins.md"

[[release_notes]]
title = "implement the full set of sort methods on QueryIter"
authors = ["@Victoronz"]
url = "https://github.com/bevyengine/bevy/pull/13417"
file_name = "13417_implement_the_full_set_of_sort_methods_on_QueryIter.md"

[[release_notes]]
title = "Implement a SystemBuilder for building SystemParams"
authors = ["@james-j-obrien"]
url = "https://github.com/bevyengine/bevy/pull/13123"
file_name = "13123_Implement_a_SystemBuilder_for_building_SystemParams.md"

[[release_notes]]
title = "Add `Distribution` access methods for `ShapeSample` trait"
authors = ["@mweatherley"]
url = "https://github.com/bevyengine/bevy/pull/13315"
file_name = "13315_Add_Distribution_access_methods_for_ShapeSample_trait.md"

[[release_notes]]
title = "New circular primitives: `Arc2d`, `CircularSector`, `CircularSegment`"
authors = ["@aristaeus","@Jondolf","@spectria-limina","@alice-i-cecile"]
url = "https://github.com/bevyengine/bevy/pull/13482"
file_name = "13482_New_circular_primitives_Arc2d_CircularSector_CircularSegme.md"

